# Generated by Django 4.0.3 on 2022-03-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.jobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='sections',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
            preserve_default=False,
        ),
    ]
